import sublime
import sublime_plugin
import weakref
from ..protocol import FileRename as FileRename, WorkspaceEdit as WorkspaceEdit
from .core.open import open_file_uri as open_file_uri
from .core.promise import Promise as Promise
from .core.protocol import Notification as Notification, Request as Request
from .core.registry import LspWindowCommand as LspWindowCommand
from .core.sessions import Session as Session
from .core.types import match_file_operation_filters as match_file_operation_filters
from .core.url import filename_to_uri as filename_to_uri
from _typeshed import Incomplete
from collections.abc import Generator

class RenamePathInputHandler(sublime_plugin.TextInputHandler):
    path: Incomplete
    def __init__(self, path: str) -> None: ...
    def name(self) -> str: ...
    def placeholder(self) -> str: ...
    def initial_text(self) -> str: ...
    def initial_selection(self) -> list[tuple[int, int]]: ...
    def validate(self, path: str) -> bool: ...

class LspRenamePathCommand(LspWindowCommand):
    capability: str
    def is_enabled(self) -> bool: ...
    def want_event(self) -> bool: ...
    def input(self, args: dict) -> sublime_plugin.TextInputHandler | None: ...
    def run(self, new_name: str, paths: list[str] | None = None) -> None: ...
    @staticmethod
    def is_case_change(path_a: str, path_b: str) -> bool: ...
    def run_async(self, old_path: str, new_path: str) -> None: ...
    def create_will_rename_requests_async(self, file_rename: FileRename) -> Generator[Promise[tuple[WorkspaceEdit | None, weakref.ref[Session]]]]: ...
    def handle_rename_async(self, responses: list[tuple[WorkspaceEdit | None, weakref.ref[Session]]]) -> Promise[None]: ...
    def rename_path(self, old: str, new: str) -> Promise[bool]: ...
    def notify_did_rename(self, file_rename: FileRename) -> None: ...
    def restore_view(self, selection: list[sublime.Region], group: tuple[int, int], view: sublime.View | None) -> None: ...
    def focus_view(self, path: str | None) -> None: ...
